src/CatalogoDeFilmes.Mvc/Models/ErrorViewModel.cs
namespace CatalogoDeFilmes.Mvc.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

src/CatalogoDeFilmes.Mvc/Controllers/DiretoresController.cs
using CatalogoDeFilmes.Application.Models;
using CatalogoDeFilmes.Application.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace CatalogoDeFilmes.Mvc.Controllers;

public class DiretoresController : Controller
{
    private readonly IDiretorService _dirService;

    public DiretoresController(IDiretorService dirService)
    {
        _dirService = dirService;
    }

    public async Task<IActionResult> Index()
    {
        var listagem = await _dirService.ListarTodos();
        return View(listagem);
    }

    [HttpGet]
    public IActionResult CadastrarDiretor()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> CadastrarDiretor(DiretoresModel diretor)
    {
        await _dirService.CadastrarDiretor(diretor);
        if (diretor.OperacaoValida == false)
        {
            return View(diretor);
        }

        return RedirectToAction("Index");
    }

    [HttpGet]
    public async Task<IActionResult> ExibirDetalhes(int id)
    {
        var diretor = await _dirService.BuscarId(id);
        return View(diretor);
    }


    [HttpGet]
    public async Task<IActionResult> EditarDiretor(int Id)
    {
        var diretor = await _dirService.BuscarId(Id);
        return View(diretor);
    }

    [HttpPost]
    public async Task<IActionResult> EditarDiretor(DiretoresModel diretor)
    {
        await _dirService.EditarDiretor(diretor);

        return RedirectToAction("Index");
    }


    [HttpGet]
    public async Task<IActionResult> ExcluirDiretor(int id)
    {
        var diretor = await _dirService.BuscarId(id); 
        return View(diretor);
    }

    [HttpPost]
    public async Task<IActionResult> ExcluirDiretor(DiretoresModel diretor)
    {
        var sucesso = await _dirService.DeletarDiretor(diretor);

        if(sucesso != null)
        {
            return RedirectToAction("Index");   
        }
            return View(diretor);
    }
}

src/CatalogoDeFilmes.Mvc/Controllers/FilmesController.cs
using CatalogoDeFilmes.Application.Models;
using CatalogoDeFilmes.Application.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CatalogoDeFilmes.Mvc.Controllers;

public class FilmesController : Controller
{
    private readonly IFilmesService _filmesService;
    private readonly IDiretorService _diretorService;

    public FilmesController(IFilmesService filmesService, IDiretorService diretorService)
    {
        _filmesService = filmesService;
        _diretorService = diretorService;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var listagem = await _filmesService.ListarTodos();
        return View(listagem);
    }

    [HttpGet]
    public async Task<IActionResult> CadastrarFilme()

    {
        var listagem = await _diretorService.ListarNomeId();
        ViewBag.ListaDiretores = new SelectList(listagem, "Id", "PrimeiroNome");
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> CadastrarFilme(FilmesModel filme, IFormFile foto)
    {
        await _filmesService.CadastrarFilme(filme, foto);
        if (filme.OperacaoValida == false) { 

            var listagem = await _diretorService.ListarNomeId();
            ViewBag.ListaDiretores = new SelectList(listagem, "Id", "PrimeiroNome");
            return View(filme);
        }

        return RedirectToAction("index");
    }

    [HttpGet]
    public async Task<IActionResult> EditarFilme(int id)
    {
        var entity = await _filmesService.BuscarId(id);
        if (entity != null)
        {
            var listagem = await _diretorService.ListarNomeId();

            ViewBag.ListaDiretores = new SelectList(listagem, "Id", "PrimeiroNome");
            return View(entity);
        }
        return NotFound();
    }

    [HttpPost]
    public async Task <IActionResult> EditarFilme(FilmesModel filme, IFormFile foto)
    {

        await _filmesService.EditarFilme(filme, foto);
        if (filme.OperacaoValida == false)
        {
            var listagem = await _diretorService.ListarNomeId();
            ViewBag.ListaDiretores = new SelectList(listagem, "Id", "PrimeiroNome");
            return View(filme);
        }

        return RedirectToAction("index");
    }

    [HttpGet]
    public async Task <IActionResult> ExcluirFilme(int id)
    {
        var entity = await _filmesService.BuscarId(id);
        if (entity != null)
        {
            var listagem = await _diretorService.ListarNomeId();

            ViewBag.ListaDiretores = new SelectList(listagem, "Id", "PrimeiroNome");
            return View(entity);
        }
        return NotFound();
    }

    [HttpPost]
    public async Task<IActionResult> ExcluirFilme(FilmesModel filme)
    {
        var entity = await _filmesService.DeletarFilme(filme);

        if (entity != null)
        {
            return RedirectToAction("Index");
        }

        
        return View(filme);
    }
}

src/CatalogoDeFilmes.Mvc/Controllers/HomeController.cs
using CatalogoDeFilmes.Application.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CatalogoDeFilmes.Mvc.Controllers;

public class HomeController : Controller
{
    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

src/CatalogoDeFilmes.Mvc/Views/Diretores/CadastrarDiretor.cshtml
@using CatalogoDeFilmes.Application.Models
@model DiretoresModel

@{
    ViewData["Title"] = "Adicionar Diretor";
}

<div class="container bg-dark p-5 rounded-5">

    <div class="mb-5 text-center ">

        <h1 class="text-light">Cadastro de Diretor</h1>

    </div>
    @if (Model?.errorMsg != null && Model.errorMsg.Any())
    {
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <ul class="mb-0">
                @foreach (var erro in Model.errorMsg)
                {
                    <li>@erro</li>
                }
            </ul>
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
    }
    <form method="post" asp-controller="Diretores" asp-action="CadastrarDiretor">
        <!--NOME-->
        <div class="mb-3">
            <label for="PrimeiroNome" class="form-label text-light">Nome:</label>
            <input type="text" class="form-control" id="PrimeiroNome" asp-for="PrimeiroNome" placeholder="Nome do(a) diretor(a) :">
            <span asp-validation-for="PrimeiroNome" class="text-danger"></span>
        </div>

        <!--SOBRENOME-->
        <div class="mb-3">
            <label for="Sobrenome" class="form-label text-light">Sobrenome do(a) diretor(a) </label>
            <input type="text" class="form-control" id="Sobrenome" asp-for="Sobrenome" placeholder="Sobrenome">
            <span asp-validation-for="Sobrenome" class="text-danger"></span>
        </div>

        <!--DATADENASCIMENTO-->
        <div class="mb-3">
            <label for="DataDeNascimento" class="form-label text-light">Data de nascimento </label>
            <input type="date" class="form-control" id="DataDeNascimento" asp-for="DataDeNascimento" placeholder="Data de nascimento">
            <span asp-validation-for="DataDeNascimento" class="text-danger"></span>
        </div>

        <!--NASCIONALIDADE-->
        <div class="mb-3">
            <label for="Nacionalidade" class="form-label text-light">País de origem do(a) diretor(a)</label>
            <input type="text" class="form-control" id="Description" asp-for="Nacionalidade" placeholder="País de origem :">
            <span asp-validation-for="Nacionalidade" class="text-danger"></span>
        </div>

        <!--SEXO DROP-->
        <div class="mb-3">
            <label for="Sexo" class="form-label text-light">Sexo do(a) diretor(a)</label>
            <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" name="Sexo" id="Sexo"  asp-for="Sexo" required>
                <option value="M">Masculino</option>
                <option value="F">Feminino</option>
                <option value="O">Outro</option>
            </select>
            <span asp-validation-for="Sexo" class="text-danger"></span>
        </div>

        <!--BOTÃO-->
        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">Adicionar <i class="bi bi-pen mx-2"></i> </button>
            <a class="btn btn-primary w-50" asp-controller="Diretores" asp-action="Index">Voltar <i class="bi bi-arrow-return-left" mx-2></i></a>

        </div>


    </form>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

src/CatalogoDeFilmes.Mvc/Views/Diretores/EditarDiretor.cshtml
@using CatalogoDeFilmes.Application.Models;
@model DiretoresModel;


@{
    ViewData["Title"] = "Atualizar Diretor";
}

<div class="container bg-dark p-5 rounded-5">

    <div class="mb-5 text-center ">

        <h1 class="text-light">Editar Diretor</h1>

    </div>

    <form method="post" asp-controller="Diretores" asp-action="EditarDiretor">
        <input type="hidden" asp-for="Id"/>

        <!--NOME-->
        <div class="mb-3">
            <label for="PrimeiroNome" class="form-label text-light">Nome:</label>
            <input type="text" class="form-control" id="PrimeiroNome" asp-for="PrimeiroNome" placeholder="Nome do(a) diretor(a) :">
            <span asp-validation-for="PrimeiroNome" class="text-danger"></span>
        </div>

        <!--SOBRENOME-->
        <div class="mb-3">
            <label for="Sobrenome" class="form-label text-light">Sobrenome do(a) diretor(a) </label>
            <input type="text" class="form-control" id="Sobrenome" asp-for="Sobrenome">
            <span asp-validation-for="Sobrenome" class="text-danger"></span>
        </div>

        <!--DATANASCIMENTO-->
        <div class="mb-3">
            <label for="DataDeNascimento" class="form-label text-light">Data de nascimento </label>
            <input type="date" class="form-control" id="DataDeNascimento" asp-for="DataDeNascimento">
            <span asp-validation-for="DataDeNascimento" class="text-danger"></span>
        </div>

        <!--NASCIONALIDADE-->
        <div class="mb-3">
            <label for="Nacionalidade" class="form-label text-light">País de origem do(a) diretor(a)</label>
            <input type="text" class="form-control" id="Description" asp-for="Nacionalidade" placeholder="País de origem :">
            <span asp-validation-for="Nacionalidade" class="text-danger"></span>
        </div>

        <!--SEXO DROP-->
        <div class="mb-3">
            <label for="Sexo" class="form-label text-light">Sexo do(a) diretor(a)</label>
            @* <input type="text" class="form-control" id="Description" asp-for="Sexo" placeholder=""> *@
            <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" name="Sexo" id="Sexo" required>
                <option value="M">Masculino</option>
                <option value="F">Feminino</option>
                <option value="O">Outro</option>
            </select>
            <span asp-validation-for="Sexo" class="text-danger"></span>
        </div>

        <!--BOTÃO-->
        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">Adicionar <i class="bi bi-pen mx-2"></i> </button>
            <a class="btn btn-primary w-50" asp-controller="Diretores" asp-action="Index">Voltar <i class="bi bi-arrow-return-left" mx-2></i></a>

        </div>


    </form>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

src/CatalogoDeFilmes.Mvc/Views/Diretores/ExcluirDiretor.cshtml
@using CatalogoDeFilmes.Application.Models
@model DiretoresModel;

@{
    ViewData["Title"] = "Excluir Diretor";
}

<div class="container bg-dark p-5 rounded-5">

    <div class="mb-5 text-center ">

        <h1 class="text-light">Excluir Diretor</h1>

    </div>

    <form method="post" asp-controller="Diretores" asp-action="ExcluirDiretor">
        <input type="hidden" asp-for="Id" />
        <!--ALERTA-->
        @if(Model.Filmes.Any())
        {
            <div class="alert alert-danger">
                <h1>ATENÇÃO</h1>
                <p>Este diretor possui @Model.Filmes.Count() cadastrados no banco, ao deleta-lo todos seus filhos serão deletados automaticamente</p>
                <p>Lista de filmes: </p>
                    @foreach(var filme in Model.Filmes)
                    {
                        <p>@filme.NomeFilme</p>
                    }
            </div>
            }
            else
            {
                <div class="alert alert-info">Este diretor não possui filmes vinculados e pode ser removido com segurança.</div>
            }


        <!--NOME-->
        <div class="mb-3">
            <label for="PrimeiroNome" class="form-label text-light">Nome:</label>
            <input disabled type="text" class="form-control" id="PrimeiroNome" asp-for="PrimeiroNome" placeholder="Nome do(a) diretor(a) :">
            <span asp-validation-for="PrimeiroNome" class="text-danger"></span>
        </div>

        <!--SOBRENOME-->
        <div class="mb-3">
            <label for="Sobrenome" class="form-label text-light">Sobrenome do(a) diretor(a) </label>
            <input disabled type="text" class="form-control" id="Sobrenome" asp-for="Sobrenome">
            <span asp-validation-for="Sobrenome" class="text-danger"></span>
        </div>

        <!--DATANASCIMENTO-->
        <div class="mb-3">
            <label for="DataDeNascimento" class="form-label text-light">Data de nascimento </label>
            <input disabled type="date" class="form-control" id="DataDeNascimento" asp-for="DataDeNascimento">
            <span asp-validation-for="DataDeNascimento" class="text-danger"></span>
        </div>

        <!--NASCIONALIDADE-->
        <div class="mb-3">
            <label for="Nacionalidade" class="form-label text-light">País de origem do(a) diretor(a)</label>
            <input Disabled type="text" class="form-control" id="Description" asp-for="Nacionalidade" placeholder="País de origem :">
            <span asp-validation-for="Nacionalidade" class="text-danger"></span>
        </div>

        <!--SEXO DROP-->
        <div class="mb-3">
            <label for="Sexo" class="form-label text-light">Sexo do(a) diretor(a)</label>
            @* <input type="text" class="form-control" id="Description" asp-for="Sexo" placeholder=""> *@
            <select Disabled class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" name="Sexo" id="Sexo" required>
                <option value="M">Masculino</option>
                <option value="F">Feminino</option>
                <option value="O">Outro</option>
            </select>
            <span asp-validation-for="Sexo" class="text-danger"></span>
        </div>

        <!--BOTÃO-->
        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">Excluir <i class="bi bi-trash2 mx-2"></i> </button>
            <a class="btn btn-primary w-50" asp-controller="Diretores" asp-action="Index">Voltar <i class="bi bi-arrow-return-left" mx-2></i></a>
        </div>


    </form>
</div>

src/CatalogoDeFilmes.Mvc/Views/Diretores/ExibirDetalhes.cshtml
@using CatalogoDeFilmes.Application.Models
@model DiretoresModel

@{
    ViewData["Title"] = "Dados Diretor";
}


<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row container d-flex justify-content-center">
            <div class="col-xl-12 col-md-12">
                <div class="card user-card-full">
                    <div class="row m-l-0 m-r-0">

                        <div class="col-sm-4 bg-c-lite-green user-profile">
                            <div class="card-block text-center text-white">
                                <div class="m-b-25">
                                    <img src="https://img.icons8.com/bubbles/100/000000/user.png" class="img-radius" alt="User-Profile-Image">
                                </div>
                                <h4 class="f-w-600">@Model.PrimeiroNome</h4>
                                <h5 class="f-w-600">@Model.Sobrenome</h5>
                                <i class=" mdi mdi-square-edit-outline feather icon-edit m-t-10 f-16"></i>
                            </div>
                        </div>


                        <div class="col-sm-8">

                            <div class="card-block">
                                <h6 class="m-b-20 p-b-5 b-b-default f-w-600">Detalhes</h6>
                                <div class="row">
                                    <div class="col-sm-6">
                                        <p class="m-b-10 f-w-600">Data de nascimento </p>
                                        <h6 class="text-muted f-w-400">@Model.DataDeNascimento.ToString("dd/MM/yyyy")</h6>
                                    </div>

                                    <div class="col-sm-6">
                                        <p class="m-b-10 f-w-600">Nascionalidade</p>
                                        <h6 class="text-muted f-w-400">@Model.Nacionalidade</h6>
                                    </div

                                    <div class="col-sm-6">
                                        <p class="m-b-10 f-w-600">Sexo</p>
                                        <h6 class="text-muted f-w-400">@Model.Sexo</h6>
                                    </div>




                                </div>
                                <h6 class="m-b-20 m-t-40 p-b-5 b-b-default f-w-600">Filmografia</h6>
                                <div class="row">
                                    <div class="col-sm-12">
                                        @if (Model.Filmes.Any())
                                        {
                                            <table class="table">
                                                <thead>
                                                    <tr>
                                                        <th>Poster</th>
                                                        <th>Nome</th>
                                                        <th>Genero</th>
                                                        <th>Lançamento</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    @foreach(var filme in Model.Filmes)
                                                    {
                                                        <tr>
                                                            <td>
                                                                <img src="/imgs/cartazes/@filme.Imagem" width="50" class="rounded"/>
                                                            </td>

                                                            <td>@filme.NomeFilme</td>
                                                            <td>@filme.Genero</td>
                                                            <td>@filme.DataLancamento.ToString("dd/MM/yyyy")</td>
                                                        </tr>
                                                    }
                                                </tbody>   
                                            </table>
                                        }
                                    </div>

                                </div>


                                <ul class="social-link list-unstyled m-t-40 m-b-10">
                                    <li><a href="#!" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="facebook" data-abc="true"><i class="mdi mdi-facebook feather icon-facebook facebook" aria-hidden="true"></i></a></li>
                                    <li><a href="#!" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="twitter" data-abc="true"><i class="mdi mdi-twitter feather icon-twitter twitter" aria-hidden="true"></i></a></li>
                                    <li><a href="#!" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="instagram" data-abc="true"><i class="mdi mdi-instagram feather icon-instagram instagram" aria-hidden="true"></i></a></li>
                                </ul>

                            </div>
                        </div>
                        <a class="btn btn-primary  " asp-controller="Diretores" asp-action="Index">Voltar <i class="bi bi-arrow-return-left" mx-2></i></a>
                        <a class="btn btn-warning" type="submit" asp-controller="Diretores" asp-action="EditarDiretor" asp-route-id="@Model.Id"><i class="bi bi-pen"></i>Editar</i> </a>
                        <a class="btn btn-danger" type="submit" asp-controller="Diretores" asp-action="ExcluirDiretor" asp-route-id="@Model.Id"><i class="bi bi-trash2"></i>Excluir</i> </a>

                    </div>

                </div>

            </div>
        </div>
    </div>
</div>

src/CatalogoDeFilmes.Mvc/Views/Diretores/Index.cshtml
@using CatalogoDeFilmes.Application.Models;
@model List<DiretoresModel>;

@{
    ViewData["Title"] = "Diretores";
}
<div class="d-flex justify-content-end mb-5">

    <a class="btn btn-success" type="submit" asp-controller="Diretores" asp-action="CadastrarDiretor"><i class="bi bi-person-add"></i> Cadastrar</i> </a>

</div>



<div class="row">
    @foreach(var diretor in Model)
    {
        <div class="col-md-4 mb-4">
            <div class="card text-white bg-dark mb-3 shadow-lg rounded h-100">
                <div class="card-body mb-2">
                    <a class="btn btn-primary float-end" alt="Detalhes" asp-controller="Diretores" asp-action="ExibirDetalhes" asp-route-id="@diretor.Id"><i class="bi bi-info-circle"></i></a>
                    <h4 class="card-title">@diretor.PrimeiroNome</h4>
                    <h5 class="card-subtitle ">@diretor.Sobrenome</h5>

                    <div class="row mt-auto d-flex  gy-3 list-group">
                        
                        <a class="btn btn-warning" asp-controller="Diretores" asp-action="EditarDiretor" asp-route-id="@diretor.Id"><i class="bi bi-pen"></i></a>
                        <a class="btn btn-danger" asp-controller="Diretores" asp-action="ExcluirDiretor" asp-route-id="@diretor.Id"><i class="bi bi-trash2"></i></a>
                    </div>


                </div>

            </div>
        </div>
    }

</div>

src/CatalogoDeFilmes.Mvc/Views/Filmes/CadastrarFilme.cshtml
@using CatalogoDeFilmes.Application.Models
@model FilmesModel

<div class="container bg-dark p-5 rounded-5">

    <div class="mb-5 text-center ">

        <h1 class="text-light">Cadastro de Filme</h1>

    </div>
    @if (Model?.errorMsg != null && Model.errorMsg.Any())
    {
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <ul class="mb-0">
                @foreach (var erro in Model.errorMsg)
                {
                    <li>Erro de entrada : @erro</li>
                }
            </ul>
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
    }


    <form method="post" asp-controller="Filmes" asp-action="CadastrarFilme" enctype="multipart/form-data">
        @* <input type="hidden" asp-for="@(ViewBag.ListaDiretores.DataDeNascimento)" /> *@
        <!--NOME-->
        <div class="mb-3">
            <label for="NomeFilme" class="form-label text-light">Nome:</label>
            <input type="text" class="form-control" id="NomeFilme" asp-for="NomeFilme" placeholder="Nome do filme :">
            <span asp-validation-for="NomeFilme" class="text-danger"></span>
        </div>

        <!--GENERO-->
        <div class="mb-3">
            <label for="Genero" class="form-label text-light">Genero do(a) diretor(a) </label>
            <input type="text" class="form-control" id="Genero" asp-for="Genero" placeholder="Gênero">
            <span asp-validation-for="Genero" class="text-danger"></span>
        </div>


        <!--DIRETOR USANDO VIEWBAG-->
        <div class="mb-3">
            <label for="DiretorId_Fk" class="form-label text-light">Selecione um diretor</label>

            <select asp-for="DiretorId_Fk" asp-items="@(ViewBag.ListaDiretores as SelectList)" class="form-select form-select-lg mb-3">
                @* <option value="">Selecione um diretor : </option> *@
            </select>
            <span asp-validation-for="DiretorId_Fk" class="text-danger"></span>
        </div>

        <!--DATA DE LANÇAMENTO-->
        <div class="mb-3">
            <label for="DataLancamento" class="form-label text-light">Data de lançamento </label>
            <input type="date" class="form-control" id="DataDeNascimento" asp-for="DataLancamento" placeholder="Data de Lançamento">
            <span asp-validation-for="DataLancamento" class="text-danger"></span>
        </div>

        <!--DURAÇÃO DO FILME-->
        <div class="mb-3">
            <label for="GeneDuracaoro" class="form-label text-light">Duração em minutos </label>
            <input type="number" class="form-control" id="Duracao" asp-for="Duracao" placeholder="Duracao">
            <span asp-validation-for="Duracao" class="text-danger"></span>
        </div>

        <!--UPLOAD DE IMAGEM-->
        <div class="mb-3">
            <label class="form-label text-light">Imagem do Filme</label>
            <input type="file" name="foto" class="form-control"  />
            <span asp-validation-for="Imagem" class="tex-danger"></span>
        </div>

        <!--NOTA DO FILME-->
        <div class="mb-3">
            <label for="Nota" class="form-label text-light">Nota do filme 1-10 </label>
            <input type="number" class="form-control" id="Nota" asp-for="Nota" placeholder="Nota">
            <span asp-validation-for="Nota" class="text-danger"></span>
        </div>

        <!--BOTÃO-->
        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">Adicionar <i class="bi bi-pen mx-2"></i> </button>
            <a class="btn btn-primary w-50" asp-controller="Filmes" asp-action="Index">Voltar <i class="bi bi-arrow-return-left" mx-2></i></a>

        </div>


    </form>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

src/CatalogoDeFilmes.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Catalogo de filmes</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CatalogoDeFilmes.Mvc.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Catalogos de filmes</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Diretores" asp-action="Index">Diretores</a>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Filmes" asp-action="Index">Filmes</a>
                        </li>



                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2026 - CatalogoDeFilmes.Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>